// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/contract/balance_contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AccountIdentifier;
@class BlockBalanceTrace_BlockIdentifier;
@class TransactionBalanceTrace;
@class TransactionBalanceTrace_Operation;
GPB_ENUM_FWD_DECLARE(ResourceCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum WithdrawBalanceContract_WithdrawBalanceType

typedef GPB_ENUM(WithdrawBalanceContract_WithdrawBalanceType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  WithdrawBalanceContract_WithdrawBalanceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WithdrawBalanceContract_WithdrawBalanceType_All = 0,
  WithdrawBalanceContract_WithdrawBalanceType_SpreadMint = 1,
};

GPBEnumDescriptor *WithdrawBalanceContract_WithdrawBalanceType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL WithdrawBalanceContract_WithdrawBalanceType_IsValidValue(int32_t value);

#pragma mark - BalanceContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BalanceContractRoot : GPBRootObject
@end

#pragma mark - FreezeBalanceContract

typedef GPB_ENUM(FreezeBalanceContract_FieldNumber) {
  FreezeBalanceContract_FieldNumber_OwnerAddress = 1,
  FreezeBalanceContract_FieldNumber_FrozenBalance = 2,
  FreezeBalanceContract_FieldNumber_FrozenDuration = 3,
  FreezeBalanceContract_FieldNumber_Resource = 10,
  FreezeBalanceContract_FieldNumber_ReceiverAddress = 15,
  FreezeBalanceContract_FieldNumber_ParentAddress = 16,
};

GPB_FINAL @interface FreezeBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) int64_t frozenBalance;

@property(nonatomic, readwrite) int64_t frozenDuration;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *parentAddress;

@end

/**
 * Fetches the raw value of a @c FreezeBalanceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t FreezeBalanceContract_Resource_RawValue(FreezeBalanceContract *message);
/**
 * Sets the raw value of an @c FreezeBalanceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetFreezeBalanceContract_Resource_RawValue(FreezeBalanceContract *message, int32_t value);

#pragma mark - UnfreezeBalanceContract

typedef GPB_ENUM(UnfreezeBalanceContract_FieldNumber) {
  UnfreezeBalanceContract_FieldNumber_OwnerAddress = 1,
  UnfreezeBalanceContract_FieldNumber_Resource = 10,
  UnfreezeBalanceContract_FieldNumber_ReceiverAddress = 15,
};

GPB_FINAL @interface UnfreezeBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) enum ResourceCode resource;

@property(nonatomic, readwrite, copy, null_resettable) NSData *receiverAddress;

@end

/**
 * Fetches the raw value of a @c UnfreezeBalanceContract's @c resource property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UnfreezeBalanceContract_Resource_RawValue(UnfreezeBalanceContract *message);
/**
 * Sets the raw value of an @c UnfreezeBalanceContract's @c resource property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUnfreezeBalanceContract_Resource_RawValue(UnfreezeBalanceContract *message, int32_t value);

#pragma mark - WithdrawBalanceContract

typedef GPB_ENUM(WithdrawBalanceContract_FieldNumber) {
  WithdrawBalanceContract_FieldNumber_OwnerAddress = 1,
  WithdrawBalanceContract_FieldNumber_Type = 2,
};

GPB_FINAL @interface WithdrawBalanceContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite) WithdrawBalanceContract_WithdrawBalanceType type;

@end

/**
 * Fetches the raw value of a @c WithdrawBalanceContract's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t WithdrawBalanceContract_Type_RawValue(WithdrawBalanceContract *message);
/**
 * Sets the raw value of an @c WithdrawBalanceContract's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetWithdrawBalanceContract_Type_RawValue(WithdrawBalanceContract *message, int32_t value);

#pragma mark - TransferContract

typedef GPB_ENUM(TransferContract_FieldNumber) {
  TransferContract_FieldNumber_OwnerAddress = 1,
  TransferContract_FieldNumber_ToAddress = 2,
  TransferContract_FieldNumber_Amount = 3,
  TransferContract_FieldNumber_Type = 4,
  TransferContract_FieldNumber_RlpData = 5,
};

GPB_FINAL @interface TransferContract : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ownerAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSData *toAddress;

@property(nonatomic, readwrite) int64_t amount;

/** if type=eth validate eth sign else validate vision sign  0 or null -> vision, 1 -> eth */
@property(nonatomic, readwrite) int64_t type;

/** eth's RLP rawData */
@property(nonatomic, readwrite, copy, null_resettable) NSData *rlpData;

@end

#pragma mark - TransactionBalanceTrace

typedef GPB_ENUM(TransactionBalanceTrace_FieldNumber) {
  TransactionBalanceTrace_FieldNumber_TransactionIdentifier = 1,
  TransactionBalanceTrace_FieldNumber_OperationArray = 2,
  TransactionBalanceTrace_FieldNumber_Type = 3,
  TransactionBalanceTrace_FieldNumber_Status = 4,
};

GPB_FINAL @interface TransactionBalanceTrace : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *transactionIdentifier;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionBalanceTrace_Operation*> *operationArray;
/** The number of items in @c operationArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger operationArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@end

#pragma mark - TransactionBalanceTrace_Operation

typedef GPB_ENUM(TransactionBalanceTrace_Operation_FieldNumber) {
  TransactionBalanceTrace_Operation_FieldNumber_OperationIdentifier = 1,
  TransactionBalanceTrace_Operation_FieldNumber_Address = 2,
  TransactionBalanceTrace_Operation_FieldNumber_Amount = 3,
};

GPB_FINAL @interface TransactionBalanceTrace_Operation : GPBMessage

@property(nonatomic, readwrite) int64_t operationIdentifier;

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - BlockBalanceTrace

typedef GPB_ENUM(BlockBalanceTrace_FieldNumber) {
  BlockBalanceTrace_FieldNumber_BlockIdentifier = 1,
  BlockBalanceTrace_FieldNumber_Timestamp = 2,
  BlockBalanceTrace_FieldNumber_TransactionBalanceTraceArray = 3,
};

GPB_FINAL @interface BlockBalanceTrace : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@property(nonatomic, readwrite) int64_t timestamp;

/**  BlockIdentifier parent_block_identifier = 4; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionBalanceTrace*> *transactionBalanceTraceArray;
/** The number of items in @c transactionBalanceTraceArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionBalanceTraceArray_Count;

@end

#pragma mark - BlockBalanceTrace_BlockIdentifier

typedef GPB_ENUM(BlockBalanceTrace_BlockIdentifier_FieldNumber) {
  BlockBalanceTrace_BlockIdentifier_FieldNumber_Hash_p = 1,
  BlockBalanceTrace_BlockIdentifier_FieldNumber_Number = 2,
};

GPB_FINAL @interface BlockBalanceTrace_BlockIdentifier : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

@property(nonatomic, readwrite) int64_t number;

@end

#pragma mark - AccountTrace

typedef GPB_ENUM(AccountTrace_FieldNumber) {
  AccountTrace_FieldNumber_Balance = 1,
  AccountTrace_FieldNumber_Placeholder = 99,
};

GPB_FINAL @interface AccountTrace : GPBMessage

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite) int64_t placeholder;

@end

#pragma mark - AccountIdentifier

typedef GPB_ENUM(AccountIdentifier_FieldNumber) {
  AccountIdentifier_FieldNumber_Address = 1,
};

GPB_FINAL @interface AccountIdentifier : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *address;

@end

#pragma mark - AccountBalanceRequest

typedef GPB_ENUM(AccountBalanceRequest_FieldNumber) {
  AccountBalanceRequest_FieldNumber_AccountIdentifier = 1,
  AccountBalanceRequest_FieldNumber_BlockIdentifier = 2,
};

GPB_FINAL @interface AccountBalanceRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AccountIdentifier *accountIdentifier;
/** Test to see if @c accountIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasAccountIdentifier;

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@end

#pragma mark - AccountBalanceResponse

typedef GPB_ENUM(AccountBalanceResponse_FieldNumber) {
  AccountBalanceResponse_FieldNumber_Balance = 1,
  AccountBalanceResponse_FieldNumber_BlockIdentifier = 2,
};

GPB_FINAL @interface AccountBalanceResponse : GPBMessage

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, strong, null_resettable) BlockBalanceTrace_BlockIdentifier *blockIdentifier;
/** Test to see if @c blockIdentifier has been set. */
@property(nonatomic, readwrite) BOOL hasBlockIdentifier;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
